apiVersion: v1
kind: Template

parameters:
  - name: NAMESPACE
    required: true

objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
        app.openshift.io/vcs-ref: ""
        app.openshift.io/vcs-uri: https://github.com/evanshortiss/knative-kafka-demo
      generation: 5
      labels:
        app: producer
        app.kubernetes.io/component: producer
        app.kubernetes.io/instance: producer
        app.kubernetes.io/name: nodejs
        app.kubernetes.io/part-of: producer
        app.openshift.io/runtime: nodejs
        app.openshift.io/runtime-version: 14-ubi8
      name: producer
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: producer
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: producer
            deploymentconfig: producer
        spec:
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/producer
            imagePullPolicy: Always
            name: producer
            ports:
            - containerPort: 8080
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
